server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 5432
  user: "quantix"
  password: ""
  dbname: "quantix"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

data:
  yahoo_api_key: ""
  tencent_api_key: ""
  cache_expiration: 3600
  max_retries: 3

ml:
  model_path: "./models"
  confidence_threshold: 0.7
  max_features: 20
  cross_validation: true

log:
  level: "info"
  format: "json"
  output: "stdout" 