version: '3.8'

services:
  quantix:
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUANTIX_SERVER_PORT=8080
      - QUANTIX_LOG_LEVEL=info
    volumes:
      - ./charts:/app/charts
      - ./models:/app/models
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - quantix-network

networks:
  quantix-network:
    driver: bridge 